### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by fenykep** [fenykep/pyproject#1]
Could you please add your names and student numbers to the readme file?
You can push an updated readme from your computer or click the pencil on the right corner when you see the contents of it. 
Here you can create issues, or anything that we should talk about, possible features or planned modifications.
Sorry, I'm way too hyped. Also maybe we could check some git tutorials, five-ten minutes just as we won't cover this in class.

**Comment by MinasMayth** [comment]
Has my name and number successfully been added to the readme? It created a fork so I'm not sure if the main branch was also updated.
