### ISSUE TITLE
Multiple matching entries

### ISSUE THREAD

**Issue by fenykep** [fenykep/pyproject#4]
If we search for a name, print out all the matching cases.
`c.fetchone()` and `c.fetchall()` can be used to iterate through the SQL output.

**Comment by MinasMayth** [comment]
Solved it! Had to change around the first name and last name searchers (rowid could stay as it is always unique), will push the changes soon

**Comment by fenykep** [comment]
Wait with the push, I'm editing stuff and I don't know what will happen.
